variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: fetch

stages:
  - build
  - test

build:linux:
  image: alpine:latest
  tags:
    - linux
  stage: build
  before_script:
    - apk add --update g++ make cmake automake libtool autoconf
  script:
    - make
  artifacts:
    paths:
      - "lokinet"

build:windows-mingw:
  image: ubuntu:latest
  tags:
    - linux
  stage: build
  before_script:
    - apt update
    - apt install --yes build-essential libtool autoconf cmake git mingw-w64
  script:
    - make -j4 windows
  artifacts:
    paths:
      - "lokinet.exe"

build:osx:
  tags:
    - osx
  stage: build
  script:
    - make
  artifacts:
    paths:
      - "lokinet"